version: "2"
plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc
exclude_patterns:
  - "UI"
checks:
  method-complexity:
    enabled: false
  similar-code:
    enabled: false
  method-lines:
    enabled: false
  return-statements:
   enabled: false