language: node_js
node_js:
  - "6"
install: npm install
services:
- postgresql
env:
- NODE_ENV=test
before_script:
- psql -c 'create database bookmeal-testDb;' -U postgres
- npm run build
- sequelize db:migrate
- sequelize db:seed:all
script: npm test

after_success: npm run coverage
