language: node_js
node_js:
  - "6"

env:
  global:
    - CC_TEST_REPORTER_ID=0feb5749de902a0661fc1db15475d972d19758fe5334f408c296d871f4eabe70
script: - npm run test

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: npm run coverage


