const getMealsResponse = {
  meals: [
    {
      id: 54,
      title: 'gfhgh',
      description: null,
      image_url: 'https://res.cloudinary.com/dffiyhgto/image/upload/v1536160768/gfhgh980.jpg',
      price: 980,
      quantity: 1,
      createdAt: '2018-09-05T15:19:29.689Z',
      updatedAt: '2018-09-05T15:19:29.689Z',
      extras: [
        {
          id: 4,
          title: 'mutton',
          category: 'OnTop',
          price: 100,
        },
        {
          id: 1,
          title: 'beef',
          category: 'GoesWith',
          price: 50,
        },
        {
          id: 2,
          title: 'chicken',
          category: 'OnTop',
          price: 150,
        },
      ],
    },
    {
      id: 53,
      title: 'Ebaaa',
      description: 'descrt',
      image_url: 'https://res.cloudinary.com/dffiyhgto/image/upload/v1536160266/vcvb546.jpg',
      price: 550,
      quantity: 1,
      createdAt: '2018-09-05T15:11:06.556Z',
      updatedAt: '2018-09-05T15:31:42.227Z',
      extras: [
        {
          id: 2,
          title: 'chicken',
          category: 'OnTop',
          price: 150,
        },
        {
          id: 1,
          title: 'beef',
          category: 'GoesWith',
          price: 50,
        },
      ],
    },
    {
      id: 51,
      title: 'Rice',
      description: null,
      image_url: 'https://res.cloudinary.com/dffiyhgto/image/upload/v1536061239/Rice1000.jpg',
      price: 1000,
      quantity: 1,
      createdAt: '2018-09-04T11:40:41.413Z',
      updatedAt: '2018-09-04T11:40:41.413Z',
      extras: [
        {
          id: 1,
          title: 'beef',
          category: 'GoesWith',
          price: 50,
        },
        {
          id: 4,
          title: 'mutton',
          category: 'OnTop',
          price: 100,
        },
        {
          id: 2,
          title: 'chicken',
          category: 'OnTop',
          price: 150,
        },
      ],
    },
    {
      id: 49,
      title: 'Basmatic Rice',
      description: 'Good for the brains.',
      image_url: 'https://res.cloudinary.com/dffiyhgto/image/upload/v1535103036/Fggg435.jpg',
      price: 435,
      quantity: 1,
      createdAt: '2018-08-24T09:30:36.495Z',
      updatedAt: '2018-09-04T04:06:11.714Z',
      extras: [
        {
          id: 1,
          title: 'beef',
          category: 'GoesWith',
          price: 50,
        },
        {
          id: 2,
          title: 'chicken',
          category: 'OnTop',
          price: 150,
        },
        {
          id: 3,
          title: 'fish',
          category: 'GoesWith',
          price: 200,
        },
      ],
    },
    {
      id: 48,
      title: 'Gbegiri ati Ewedu',
      description: 'Bon Appetite! Eating tasty meals makes times spent in the outdoors all the more enjoyable. We take great pride in our campfire culinary skills; providing delicious, hearty meals is an important part of all our trips.',
      image_url: 'https://res.cloudinary.com/dffiyhgto/image/upload/v1535101156/fdgfg340.jpg',
      price: 900,
      quantity: 1,
      createdAt: '2018-08-24T08:59:16.667Z',
      updatedAt: '2018-08-24T23:32:14.663Z',
      extras: [],
    },
    {
      id: 43,
      title: 'Dodo',
      description: null,
      image_url: '',
      price: 340,
      quantity: 1,
      createdAt: '2018-08-24T06:12:34.594Z',
      updatedAt: '2018-08-24T06:12:34.594Z',
      extras: [
        {
          id: 1,
          title: 'beef',
          category: 'GoesWith',
          price: 50,
        },
        {
          id: 3,
          title: 'fish',
          category: 'GoesWith',
          price: 200,
        },
      ],
    },
    {
      id: 42,
      title: 'Ogbonnax',
      description: 'Ogbonna is a meal that xy&#x27;s and z',
      image_url: 'https:&#x2F;&#x27;res.cloudinary.com&#x2F;dffiyhgto&#x2F;image&#x2F;upload&#x2F;v1533443184&#x2F;Asanka509.jpg',
      price: 350,
      quantity: 1,
      createdAt: '2018-08-21T05:50:29.618Z',
      updatedAt: '2018-08-21T06:11:59.265Z',
      extras: [],
    },
    {
      id: 41,
      title: 'Ogbonna',
      description: 'Ogbonna is a meal that xy&#x27;s and z',
      image_url: 'https:&#x2F;&#x2F;res.cloudinary.com&#x2F;dffiyhgto&#x2F;image&#x2F;upload&#x2F;v1533443184&#x2F;Asanka509.jpg',
      price: 350,
      quantity: 1,
      createdAt: '2018-08-21T05:46:40.200Z',
      updatedAt: '2018-08-21T06:14:03.114Z',
      extras: [
        {
          id: 4,
          title: 'mutton',
          category: 'OnTop',
          price: 100,
        },
        {
          id: 1,
          title: 'beef',
          category: 'GoesWith',
          price: 50,
        },
        {
          id: 2,
          title: 'chicken',
          category: 'OnTop',
          price: 150,
        },
        {
          id: 3,
          title: 'fish',
          category: 'GoesWith',
          price: 200,
        },
      ],
    },
    {
      id: 38,
      title: 'Asanka',
      description: null,
      image_url: 'https://res.cloudinary.com/dffiyhgto/image/upload/v1533443184/Asanka509.jpg',
      price: 509,
      quantity: 1,
      createdAt: '2018-08-05T04:26:25.598Z',
      updatedAt: '2018-08-05T04:26:25.598Z',
      extras: [],
    },
    {
      id: 1,
      title: 'rice',
      description: 'fdfdhdufdfg',
      image_url: 'jhdfjhdfhjdfhjfd',
      price: 450,
      quantity: 1,
      createdAt: '2018-06-10T04:55:40.696Z',
      updatedAt: '2018-06-10T04:55:40.696Z',
      extras: [
        {
          id: 3,
          title: 'fish',
          category: 'GoesWith',
          price: 200,
        },
        {
          id: 2,
          title: 'chicken',
          category: 'OnTop',
          price: 150,
        },
        {
          id: 1,
          title: 'beef',
          category: 'GoesWith',
          price: 50,
        },
      ],
    },
    {
      id: 2,
      title: 'abka atam',
      description: 'fdfdhdufdfg',
      image_url: 'jhdfjhdfhjdfhjfd',
      price: 430,
      quantity: 1,
      createdAt: '2018-06-10T04:55:40.696Z',
      updatedAt: '2018-06-10T04:55:40.696Z',
      extras: [
        {
          id: 1,
          title: 'beef',
          category: 'GoesWith',
          price: 50,
        },
        {
          id: 3,
          title: 'fish',
          category: 'GoesWith',
          price: 200,
        },
      ],
    },
  ],
  pagination: {
    totalCount: 11,
    limit: 30,
    offset: 0,
    totalPages: 1,
    pageNum: 1,
  },
};

const saveMealResponse = {

}

export { getMealsResponse, saveMealResponse };
