export const CREATE_USER = 'CREATE_USER';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const LOG_OUT = 'LOG_OUT';

export const LOAD_MENU = 'LOAD_MENU';
export const LOAD_MENU_SUCCESS = 'LOAD_MENU_SUCCESS';
export const CREATE_MENU_SUCCESS = 'CREATE_MENU_SUCCESS';

export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';

export const LOAD_MEAL = 'LOAD_MEAL';
export const LOAD_MEAL_SUCCESS = 'LOAD_MEAL_SUCCESS';
export const LOAD_ONE_MEAL_SUCCESS = 'LOAD_ONE_MEAL_SUCCESS';
export const CREATE_MEAL_SUCCESS = 'CREATE_MEAL_SUCCESS';
export const UPDATE_MEAL_SUCCESS = 'UPDATE_MEAL_SUCCESS';
export const DELETE_MEAL_SUCCESS = 'DELETE_MEAL_SUCCESS';

export const LOAD_EXTRA = 'LOAD_EXTRA';
export const LOAD_EXTRA_SUCCESS = 'LOAD_EXTRA_SUCCESS';
