export const CREATE_USER = 'CREATE_USER';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const LOAD_MENU = 'LOAD_MENU';
export const LOAD_MENU_SUCCESS = 'LOAD_MENU_SUCCESS';

export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';

